apiVersion: v1
kind: Service
metadata:
  name: {{ include "north-mini-code.fullname" . }}
  labels:
    {{- include "north-mini-code.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: inference
spec:
  type: ClusterIP
  selector:
    {{- include "north-mini-code.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
